insert into ieda_user ( user_id, user_password, user_name, email, role_id, init_pass_yn, create_user_id, create_date, update_user_id, update_date ) 
values ( 'admin', HEX(AES_ENCRYPT('admin', 'raison')), '관리자', 'admin@example.com', 1000, 'Y', 'system', now(), 'system', now());

#common_code Iaas Type
INSERT INTO ieda_common_code VALUES ( 100, 'IAAS TYPE', '100' , 'IaaS 유형', 'IaaS Type', 0, null, null, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 101, 'OPENSTACK', '101' , 'OpenStack', 'Open Source', 0, null, 100, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 102, 'VSPHERE', '102' , 'vSphere', 'VMWare vSphere', 1, null, 100, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 103, 'AWS', '103' , 'AWS', 'Amazon Web Service', 2, null, 100, 'SYSTEM', now(), 'SYSTEM', now() );

#common_code OS Type
INSERT INTO ieda_common_code VALUES ( 200, 'OS TYPE', '200' , 'OS 유형', 'OS Type', 1, null, null, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 201, 'UBUNTU', '201' , '우분투', 'Ubuntu', 0, null, 200, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 202, 'CENTOS', '202' , 'CentOS', 'CentOS', 1, null, 200, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 211, 'TRUSTY', '211' , 'Trusty', 'Ubuntu Trusty', 0, 201, 200, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 212, 'LUCID', '212' , 'Lucid', 'Ubuntu Lucid', 1, 201, 200, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 221, '7.X', '221' , '7.x', 'CentOS 7.x', 0, 202, 200, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 222, '6.X', '222' , '6.x', 'CentOS 6.x', 1, 202, 200, 'SYSTEM', now(), 'SYSTEM', now() );


#common_code Deploy
INSERT INTO ieda_common_code VALUES ( 312, 'DEPLOY', '1000' , 'Deploy', 'Deploy', 0, null, null, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 313, 'DEPLOY_TYPE', '1100' , '배포 유형', '배포 유형(bootstrap/bosh/cf/diego)', 0, null, 1000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 314, 'DEPLOY_TYPE_BOOTSTRAP', '1101' , 'BOOTSTRAP', 'BootStrap 배포', 1, 1100, 1000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 315, 'DEPLOY_TYPE_BOSH', '1102' , 'BOSH', 'Bosh 배포', 2, 1100, 1000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 316, 'DEPLOY_TYPE_CF', '1103' , 'CF', 'CF 배포', 3, 1100, 1000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 317, 'DEPLOY_TYPE_DIEGO', '1104' , 'DIEGO', 'Diego 배포', 4, 1100, 1000, 'SYSTEM', now(), 'SYSTEM', now() );

INSERT INTO ieda_common_code VALUES ( 318, 'DEPLOY_STATUS', '1200' , '배포 유형', '배포 상태(진행 중/완료/취소/실패)', 0, null, 1000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 319, 'DEPLOY_STATUS_PROCESSING', '1201' , '진행중', '배포 진행중', 1, 1200, 1000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 320, 'DEPLOY_STATUS_DONE', '1202' , '완료', '배포 완료', 2, 1200, 1000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 321, 'DEPLOY_STATUS_UPDATING', '1203' , '수정중', '배포 정보 수정중', 3, 1200, 1000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 322, 'DEPLOY_STATUS_CANCELLED', '1204' , '취소', '배포 취소', 4, 1200, 1000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 323, 'DEPLOY_STATUS_FAILED', '1205' , '실패', '배포 실패', 5, 1200, 1000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 324, 'DEPLOY_STATUS_DELETING', '1206' , '삭제중', '배포 삭제중', 6, 1200, 1000, 'SYSTEM', now(), 'SYSTEM', now() );

#common_code Release
INSERT INTO ieda_common_code VALUES ( 325, 'RELEASE_TYPE', '2000' , '릴리즈 유형', '릴리즈 유형', 0, null, null, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 326, 'BOSH', '2001' , 'bosh 릴리즈', 'bosh 릴리즈', 0, null, 2000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 327, 'BOSH_CPI', '2002' , 'bosh-cpi 릴리즈', 'bosh-cpi 릴리즈', 1, null, 2000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 328, 'CF', '2003' , 'cf 릴리즈', 'cf 릴리즈', 2, null, 2000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 329, 'DIEGO', '2004' , 'diego 릴리즈', 'diego 릴리즈', 3, null, 2000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 330, 'CFLINUXFS2-ROOT', '2005' , 'cflinuxfs2-root 릴리즈', 'cflinuxfs2-root 릴리즈', 4, null, 2000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 331, 'GARDEN_LINUX', '2006' , 'garden-linux 릴리즈', 'garden-linux 릴리즈', 5, null, 2000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 332, 'ETCD', '2007' , 'etcd-release 릴리즈', 'etcd-release 릴리즈', 6, null, 2000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 333, 'ETC', '2010' , '기타 릴리즈', '기타 릴리즈', 7, null, 2000, 'SYSTEM', now(), 'SYSTEM', now() );


#common_code ROLE
INSERT INTO ieda_common_code VALUES ( 334, 'ROLE', '10000' , '메뉴 별 권한', '메뉴 별 권한', 0, null, null, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 335, 'DASHBOARD', '10100' , 'DASHBOARD 조회', '/main/dashboard/**', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 336, 'CONFIG_DIRECTOR_MENU', '11000' , '설치관리자 설정_메뉴', '/config/director', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 337, 'CONFIG_DIRECTOR_LIST', '11001' , '설치관리자 조회', '/config/director/list', 1, 11000, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 338, 'CONFIG_DIRECTOR_SET', '11002' , '기본 설치관리자 설정', '/config/director/setDefault/**', 2, 11000, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 339, 'CONFIG_DIRECTOR_ADD', '11003' , '설치관리자 추가', '/config/director/add', 3, 11000, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 340, 'CONFIG_DIRECTOR_UPDATE', '11004' , '설치관리자 수정', '/config/director/update/**', 4, 11000, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 341, 'CONFIG_DIRECTOR_DELETE', '11005' , '설치관리자 삭제', '/config/director/delete/**', 5, 11000, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 342, 'CONFIG_STEMCELL_MENU', '11100' , '스템셀 관리 메뉴', '/config/stemcell', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 343, 'CONFIG_STEMCELL_LIST', '11101' , '스템셀 조회', '/config/stemcell/publicStemcells', 1, 11100, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 344, 'CONFIG_STEMCELL_SYNC', '11102' , '스템셀 목록 동기화', '/config/stemcell/syncPublicStemcell', 2, 11100, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 345, 'CONFIG_STEMCELL_DOWNLOAD', '11103' , '스템셀 다운로드', '/config/stemcell/download/**', 3, 11100, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 346, 'CONFIG_STEMCELL_DELETE', '11104' , '스템셀 삭제', '/config/stemcell/deletePublicStemcell', 4, 11100, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 347, 'CONFIG_RELEASE_MENU', '11200' , '릴리즈 관리 메뉴', '/config/systemRelease', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 348, 'CONFIG_RELEASE_LIST', '11201' , '시스템 릴리즈 조회', '/config/systemRelease/list/**', 1, 11200, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 349, 'CONFIG_RELEASE_REGIST', '11202' , '시스템 릴리즈 등록', '/config/systemRelease/regist/**', 2, 11200, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 350, 'CONFIG_RELEASE_DELETE', '11203' , '시스템 릴리즈 삭제', '/config/systemRelease/delete', 3, 11200, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 351, 'ADMIN_CODE_MENU', '12000' , '코드 관리', '/admin/code/**', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 352, 'ADMIN_ROLE_MENU', '12100' , '권한 관리', '/admin/role/**', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 353, 'ADMIN_USER_MENU', '12200' , '사용자 관리', '/admin/user/**', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 354, 'DEPLOY_BOOTSTRAP_MENU', '13000' , 'BOOTSTRAP 메뉴', '/deploy/bootstrap', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 355, 'DEPLOY_BOOTSTRAP_LIST', '13001' , 'BOOTSTRAP 조회', '/deploy/bootstrap/list/**', 1, 13000, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 356, 'DEPLOY_BOOTSTRAP_INSTALL', '13002' , 'BOOTSTRAP 설치', '/deploy/bootstrap/install/**', 2, 13000, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 357, 'DEPLOY_BOOTSTRAP_DELETE', '13003' , 'BOOTSTRAP 삭제', '/deploy/bootstrap/delete/**', 3, 13000, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 358, 'DEPLOY_BOSH_MENU', '13100' , 'BOSH 메뉴', '/deploy/bosh', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 359, 'DEPLOY_BOSH_LIST', '13101' , 'BOSH 조회', '/deploy/bosh/list/**', 1, 13100, 10000, 'SYSTEM', now(), 'SYSTEM', now());
INSERT INTO ieda_common_code VALUES ( 360, 'DEPLOY_BOSH_INSTALL', '13102' , 'BOSH 설치', '/deploy/bosh/install/**', 2, 13100, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 361, 'DEPLOY_BOSH_DELETE', '13103' , 'BOSH 삭제', '/deploy/bosh/delete/**', 3, 13100, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 362, 'DEPLOY_CF_MENU', '13200' , 'CF 메뉴', '/deploy/cf', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 363, 'DEPLOY_CF_LIST', '13201' , 'CF 조회', '/deploy/cf/list/**', 1, 13200, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 364, 'DEPLOY_CF_INSTALL', '13202' , 'CF 설치', '/deploy/cf/install/**', 2, 13200, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 365, 'DEPLOY_CF_DELETE', '13203' , 'CF 삭제', '/deploy/cf/delete/**', 3, 13200, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 366, 'DEPLOY_DIEGO_MENU', '13300' , 'Diego 메뉴', '/deploy/diego', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 367, 'DEPLOY_DIEGO_LIST', '13301' , 'Diego 조회', '/deploy/diego/list/**', 1, 13300, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 368, 'DEPLOY_DIEGO_INSTALL', '13302' , 'Diego 설치', '/deploy/diego/install/**', 2, 13300, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 369, 'DEPLOY_DIEGO_DELETE', '13303' , 'Diego 삭제', '/deploy/diego/delete/**', 3, 13300, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 370, 'DEPLOY_CF_DIEGO_MENU', '13400' , 'CF & Diego 메뉴', '/deploy/cfDiego', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 371, 'DEPLOY_CF_DIEGO_LIST', '13401' , 'CF & Diego 조회', '/deploy/cfDiego/list/**', 1, 13400, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 372, 'DEPLOY_CF_DIEGO_INSTALL', '13402' , 'CF & Diego 통합 설치', '/deploy/cfDiego/install/**', 2, 13400, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 373, 'DEPLOY_CF_DIEGO_DELETE', '13403' , 'CF & Diego 삭제', '/deploy/cfDiego/delete/**', 3, 13400, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 374, 'INFO_STEMCELL_MENU', '14000' , '스템셀 업로드 메뉴', '/info/stemcell', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 375, 'INFO_STEMCELL_LIST', '14001' , '스템셀 업로드 조회', '/info/stemcell/list/**', 1, 14000, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 376, 'INFO_STEMCELL_UPLOAD', '14002' , '스템셀 업로드', ' info/stemcell/upload/**', 2, 14000, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 377, 'INFO_STEMCELL_DELETE', '14003' , '스템셀 업로드 삭제', '/info/stemcell/delete/**', 3, 14000, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 378, 'INFO_RELEASE_MENU', '14100' , '릴리즈 업로드 메뉴', '/info/release', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 379, 'INFO_RELEASE_LIST', '14101' , '릴리즈 업로드 조회', '/info/release/list/**', 1, 14100, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 380, 'INFO_RELEASE_UPLOAD', '14102' , '릴리즈 업로드', '/info/release/upload/**', 2, 14100, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 381, 'INFO_RELEASE_DELETE', '14103' , '릴리즈 업로드 삭제', '/info/release/delete/**', 3, 14100, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 382, 'INFO_DEPLOYMENT_MENU', '14200' , '배포 정보 메뉴', '/info/deployment', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 383, 'INFO_DEPLOYMENT_LIST', '14201' , '배포 정보 조회', '/info/deployment/list', 1, 14200, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 384, 'INFO_TASK_MENU', '14300' , 'TASK 메뉴', '/info/task', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 385, 'INFO_TASK_LIST', '14301' , 'TASK 조회', '/info/task/list', 1, 14300, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 386, 'INFO_TASK_DEBUG', '14302' , 'TASK 디버그 로그', '/info/task/list/debugLog/{id}', 2, 14300, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 387, 'INFO_TASK_EVENT', '14303' , 'TASK 이벤트 로그', '/info/task/list/eventLog/**', 3, 14300, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 388, 'INFO_VM_MENU', '14400' , 'VM 메뉴', '/info/vms', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 389, 'INFO_VM_LIST', '14401' , 'VM 조회', '/info/vms/list/**', 1, 14400, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 390, 'INFO_VM_LOG', '14402' , 'VM 로그 다운로드', '/info/vms/vmLogs/**', 2, 14400, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 391, 'INFO_VM_JOB', '14403' , 'VM JOB 관리', '/info/vms/eventLog/**', 3, 14400, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 392, 'INFO_VM_SNAPSHOT', '14404' , 'VM 스냅샷 생성', '/info/vms/snapshotLog/**', 4, 14400, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 393, 'INFO_PROPERTY_MENU', '14500' , 'Property 메뉴', '/info/property', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 394, 'INFO_PROPERTY_LIST', '14501' , 'Property 조회', '/info/property/list/**', 1, 14500, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 395, 'INFO_PROPERTY_MODIFY', '14502' , 'Property 생성/수정/삭제', '/info/property/modify/**', 2, 14500, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 396, 'INFO_SNAPSHOT_MENU', '14600' , '스냅샷 메뉴', '/info/snapshot', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 397, 'INFO_SNAPSHOT_LIST', '14601' , '스냅샷 조회', '/info/snapshot/list/**', 1, 14600, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 398, 'INFO_SNAPSHOT_DELETE', '14602' , '스냅샷 삭제', '/info/snapshot/delete/**', 2, 14600, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 399, 'INFO_MANIFEST_MENU', '14700' , 'Manifest 메뉴', '/info/manifest', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 400, 'INFO_MANIFEST_LIST', '14701' , 'Manifest 조회', '/info/manifest/list', 1, 14700, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 401, 'INFO_MANIFEST_UPLOAD', '14702' , 'Manifest 업로드', '/info/manifest/upload', 2, 14700, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 402, 'INFO_MANIFEST_DOWNLOAD', '14703' , 'Manifest 다운로드', '/info/manifest/download', 3, 14700, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 403, 'INFO_MANIFEST_UPDATE', '14704' , 'Manifest 수정', '/info/manifest/update/**', 4, 14700, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 404, 'INFO_MANIFEST_DELETE', '14705' , 'Manifest 삭제', '/info/manifest/delete', 5, 14700, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 405, 'DEPLOY_SERVICEPACK_MENU', '14800' , '서비스팩 메뉴', '/deploy/servicePack', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 406, 'DEPLOY_SERVICEPACK_LIST', '14801' , '서비스팩 조회', '/deploy/servicePack/list/**', 1, 14800, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 407, 'DEPLOY_SERVICEPACK_INSTALL', '14802' , '서비스팩 설치', '/deploy/servicePack/install/**', 2, 14800, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 408, 'DEPLOY_SERVICEPACK_DELETE', '14803' , '서비스팩 삭제', '/deploy/servicePack/delete/**', 3, 14800, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 409, 'COMMON_SYSTEM_USER', '19000' , '기본 시스템 사용자 권한', '/common/user/**', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 410, 'COMMON_SYSTEM_USE', '19100' , '기본 시스템 조회 권한', '/common/use/**', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_common_code VALUES ( 411, 'COMMON_SYSTEM_DEPLOY', '19200' , '기본 시스템 배포 권한', '/common/deploy/**', 0, null, 10000, 'SYSTEM', now(), 'SYSTEM', now() );

#ROLE
Insert into ieda_role ( role_id, role_name, role_description, create_user_id, create_date, update_user_id, update_date )  values ( '1000', 'ADMIN', 'ADMIN', 'SYSTEM', now(), 'SYSTEM', now());
Insert into ieda_role ( role_id, role_name, role_description, create_user_id, create_date, update_user_id, update_date )  values ( '1001', 'DEPLOY_USER', 'DEPLOY_USER', 'SYSTEM', now(), 'SYSTEM', now());

INSERT INTO ieda_role_detail VALUES ( 1000, '0', '11000', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '11001', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '11002', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '11003', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '4', '11004', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '5', '11005', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '11100', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '11101', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '11102', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '11103', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '4', '11104', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '11200', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '11201', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '11202', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '11203', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '12000', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '12100', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '12200', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '13000', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '13001', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '13002', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '13003', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '13100', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '13101', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '13102', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '13103', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '13200', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '13201', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '13202', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '13203', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '13300', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '13301', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '13302', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '13303', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '13400', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '13401', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '13402', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '13403', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '14000', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '14001', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '14002', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '14003', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '14100', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '14101', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '14102', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '14103', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '14200', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '14201', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '14300', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '14301', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '14302', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '14303', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '14400', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '14401', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '14402', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '14403', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '4', '14404', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '14500', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '14501', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '14502', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '14600', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '14601', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '14602', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '14700', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '14701', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '14702', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '14703', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '4', '14704', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '5', '14705', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '14800', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '14801', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '14802', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '14803', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '10100', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '1', '10101', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '2', '10102', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '3', '10103', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '4', '10104', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '19000', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '19100', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1000, '0', '19200', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '11000', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '11001', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '11002', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '11003', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '4', '11004', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '5', '11005', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '11100', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '11101', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '11102', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '11103', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '4', '11104', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '11200', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '11201', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '11202', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '11203', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '13000', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '13001', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '13002', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '13003', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '13100', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '13101', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '13102', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '13103', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '13200', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '13201', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '13202', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '13203', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '13300', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '13301', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '13302', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '13303', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '13400', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '13401', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '13402', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '13403', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '14000', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '14001', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '14002', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '14003', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '14100', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '14101', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '14102', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '14103', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '14200', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '14201', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '14300', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '14301', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '14302', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '14303', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '14400', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '14401', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '14402', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '14403', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '4', '14404', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '14500', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '14501', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '14502', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '14600', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '14601', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '14602', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '14700', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '14701', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '14702', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '14703', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '4', '14704', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '5', '14705', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '14800', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '14801', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '14802', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '14803', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '10100', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '1', '10101', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '2', '10102', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '3', '10103', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '4', '10104', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '19000', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '19100', 'SYSTEM', now(), 'SYSTEM', now() );
INSERT INTO ieda_role_detail VALUES ( 1001, '0', '19200', 'SYSTEM', now(), 'SYSTEM', now() );

#manifest tamplate info
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('BOOTSTRAP','aws','bosh','233','233','generic_manifest_mask.yml','', '', 'aws-microbosh-stub.yml','','','','','aws-microbosh-param.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('BOOTSTRAP','openstack','bosh','233','233','generic_manifest_mask.yml','', '', 'openstack-microbosh-stub.yml','','','','','openstack-microbosh-param.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('BOOTSTRAP','aws','bosh','256','256','generic_manifest_mask.yml','bootstrap.yml', '', '','','','','bootstrap_aws_stub_256.yml','bootstrap_aws_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('BOOTSTRAP','openstack','bosh','256','256','generic_manifest_mask.yml','bootstrap.yml', '', '','','','','bootstrap_openstack_stub_256.yml','bootstrap_openstack_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('BOOTSTRAP','vsphere','bosh','256','256','generic_manifest_mask.yml','bootstrap.yml', '', '','','','','bootstrap_vsphere_stub_256.yml','bootstrap_vsphere_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('BOSH','aws','bosh','233','233','generic_manifest_mask.yml','', '', 'aws-bosh-stub.yml','','','','','aws-bosh-param.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('BOSH','openstack','bosh','233','233','generic_manifest_mask.yml','', '', 'openstack-bosh-stub.yml','','','','','openstack-bosh-param.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('BOSH','aws','bosh','256','256','generic_manifest_mask.yml','bosh.yml', '', '','','','','bosh_aws_stub_256.yml','bosh_aws_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('BOSH','openstack','bosh','256','256','generic_manifest_mask.yml','bosh.yml', '', '','','','','bosh_openstack_stub_256.yml','bosh_openstack_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('BOSH','vsphere','bosh','256','256','generic_manifest_mask.yml','bosh.yml', '', '','','','','bosh_vsphere_stub_256.yml','bosh_vsphere_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','aws','cf','226','226','generic_manifest_mask.yml','', '', 'aws-cf-stub.yml','','','','','aws-cf-param.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','openstack','cf','226','226','generic_manifest_mask.yml','', '', 'openstack-cf-stub.yml','','','','','openstack-cf-param.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','aws','openpaas-controller','226','1.0','generic_manifest_mask.yml','', '', 'aws-cf-stub.yml','','','','','aws-cf-param.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','openstack','openpaas-controller','226','1.0','generic_manifest_mask.yml','', '', 'openstack-cf-stub.yml','','','','','openstack-cf-param.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','aws','cf','236','236','generic_manifest_mask.yml','cf.yml', 'cf_diego_options.yml', 'cf_aws_settings.yml','cf_aws_network_options.yml','cf_aws_resouce_options.yml','','cf_aws_stub_236.yml','cf_aws_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','openstack','cf','236','236','generic_manifest_mask.yml','cf.yml', 'cf_diego_options.yml', 'cf_openstack_settings.yml','cf_openstack_network_options.yml','cf_openstack_resouce_options.yml','','cf_openstack_stub_236.yml','cf_openstack_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','vsphere','cf','236','236','generic_manifest_mask.yml','cf.yml', 'cf_diego_options.yml', 'cf_vsphere_settings.yml','cf_vsphere_network_options.yml','cf_vsphere_resouce_options.yml','','cf_vsphere_stub_236.yml','cf_vsphere_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','aws','cf','237','237','generic_manifest_mask.yml','cf.yml', 'cf_diego_options.yml', 'cf_aws_settings.yml','cf_aws_network_options.yml','cf_aws_resouce_options.yml','','cf_aws_stub_237.yml','cf_aws_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','openstack','cf','237','237','generic_manifest_mask.yml','cf.yml', 'cf_diego_options.yml', 'cf_openstack_settings.yml','cf_openstack_network_options.yml','cf_openstack_resouce_options.yml','','cf_openstack_stub_237.yml','cf_openstack_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','vsphere','cf','237','237','generic_manifest_mask.yml','cf.yml', 'cf_diego_options.yml', 'cf_vsphere_settings.yml','cf_vsphere_network_options.yml','cf_vsphere_resouce_options.yml','','cf_vsphere_stub_237.yml','cf_vsphere_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','aws','cf','241','241','generic_manifest_mask.yml','cf.yml', 'cf_diego_options.yml', 'cf_aws_settings.yml','cf_aws_network_options.yml','cf_aws_resouce_options.yml','','cf_aws_stub_241.yml','cf_aws_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','openstack','cf','241','241','generic_manifest_mask.yml','cf.yml', 'cf_diego_options.yml', 'cf_openstack_settings.yml','cf_openstack_network_options.yml','cf_openstack_resouce_options.yml','','cf_openstack_stub_241.yml','cf_openstack_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','vsphere','cf','241','241','generic_manifest_mask.yml','cf.yml', 'cf_diego_options.yml', 'cf_vsphere_settings.yml','cf_vsphere_network_options.yml','cf_vsphere_resouce_options.yml','','cf_vsphere_stub_241.yml','cf_vsphere_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','aws','cf','242','242','generic_manifest_mask.yml','cf.yml', 'cf_diego_options.yml', 'cf_aws_settings.yml','cf_aws_network_options.yml','cf_aws_resouce_options.yml','','cf_aws_stub_242.yml','cf_aws_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','openstack','cf','242','242','generic_manifest_mask.yml','cf.yml', 'cf_diego_options.yml', 'cf_openstack_settings.yml','cf_openstack_network_options.yml','cf_openstack_resouce_options.yml','','cf_openstack_stub_242.yml','cf_openstack_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('CF','vsphere','cf','242','242','generic_manifest_mask.yml','cf.yml', 'cf_diego_options.yml', 'cf_vsphere_settings.yml','cf_vsphere_network_options.yml','cf_vsphere_resouce_options.yml','','cf_vsphere_stub_242.yml','cf_vsphere_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('DIEGO','aws','openpaas-container','0.1442.0','1.0','generic_manifest_mask.yml','', '', 'aws-diego-stub.yml','','','','','aws-diego-param.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('DIEGO','openstack','openpaas-container','0.1442.0','1.0','generic_manifest_mask.yml','', '', 'openstack-diego-stub.yml','','','','','openstack-diego-param.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('DIEGO','aws','diego','0.1442.0','0.1442.0','generic_manifest_mask.yml','', '', 'aws-diego-stub.yml','','','','','aws-diego-param.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('DIEGO','openstack','diego','0.1442.0','0.1442.0','generic_manifest_mask.yml','', '', 'openstack-diego-stub.yml','','','','','openstack-diego-param.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('DIEGO','aws','diego','0.1481.0','0.1481.0','generic_manifest_mask.yml','diego.yml', '', 'diego_aws_settings.yml','diego_aws_network_1.yml','','diego_aws_network_2.yml','diego_stub_0.1481.0.yml','diego_aws_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('DIEGO','openstack','diego','0.1481.0','0.1481.0','generic_manifest_mask.yml','diego.yml', '', 'diego_openstack_settings.yml','diego_openstack_network_1.yml','','diego_openstack_network_2.yml','diego_stub_0.1481.0.yml','diego_openstack_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('DIEGO','vsphere','diego','0.1481.0','0.1481.0','generic_manifest_mask.yml','diego.yml', '', 'diego_vsphere_settings.yml','diego_vsphere_network_1.yml','','diego_vsphere_network_2.yml','diego_stub_0.1481.0.yml','diego_vsphere_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('DIEGO','aws','diego','0.1483.0','0.1483.0','generic_manifest_mask.yml','diego.yml', '', 'diego_aws_settings.yml','diego_aws_network_1.yml','','diego_aws_network_2.yml','diego_stub_0.1483.0.yml','diego_aws_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('DIEGO','openstack','diego','0.1483.0','0.1483.0','generic_manifest_mask.yml','diego.yml', '', 'diego_openstack_settings.yml','diego_openstack_network_1.yml','','diego_openstack_network_2.yml','diego_stub_0.1483.0.yml','diego_openstack_inputs.yml','SYSTEM',now(),'SYSTEM',now());
INSERT INTO ieda_manifest_template (deploy_type, iaas_type, release_type, template_version, min_release_version, common_base_template, common_job_template, common_option_template, iaas_property_template, option_network_template, option_resource_template, option_etc, meta_template, input_template, create_user_id, create_date, update_user_id, update_date) VALUES ('DIEGO','vsphere','diego','0.1483.0','0.1483.0','generic_manifest_mask.yml','diego.yml', '', 'diego_vsphere_settings.yml','diego_vsphere_network_1.yml','','diego_vsphere_network_2.yml','diego_stub_0.1483.0.yml','diego_vsphere_inputs.yml','SYSTEM',now(),'SYSTEM',now());
