#!/bin/sh

set -e -x

pushd `dirname "$0"`/..
  scripts/diego/generate-diego-ca-certs
  scripts/diego/generate-bbs-certs diego-ca diego-certs
  scripts/diego/generate-etcd-certs etcd-peer-ca diego-certs diego-ca diego-certs
popd

echo "Outputed certs to diego-certs"
