meta: ~

networks:
  - name: cf2
    type: manual
    subnets:
    - range: (( meta.network-1-range ))
      gateway: (( meta.network-1-gateway ))
      reserved: (( meta.network-1-reserved ))
      dns: (( meta.network-1-dns ))
      static: (( meta.network-1-static ))
      cloud_properties:
        net_id: (( meta.network-1-net-id ))
        security_groups: (( meta.network-1-security-groups ))

jobs:
  - name: nats_z2
    instances: (( merge || 1 ))
    networks:
      - name: cf2
        static_ips: (( static_ips(2) ))

  - name: router_z2
    instances: (( merge || 1 ))
    networks:
      - name: cf2
        static_ips: (( static_ips(5) ))

  - name: etcd_z2
    instances: (( merge || 1 ))
    networks:
      - name: cf2
        static_ips: (( static_ips(8, 9, 10) ))

  - name: consul_z2
    instances: (( merge || 1 ))
    networks:
      - name: cf2
        static_ips: (( static_ips(12, 13, 14) ))

  - name: loggregator_z2
    instances: (( merge || 0 ))
    networks:
     - name: cf2

  - name: doppler_z2
    instances: (( merge || 1 ))
    networks:
      - name: cf1

  - name: loggregator_trafficcontroller_z2
    instances: (( merge || 1 ))
    networks:
      - name: cf2

  - name: uaa_z2
    instances: (( merge || 1 ))

  - name: api_z2
    instances: (( merge || 1 ))

  - name: api_worker_z2
    instances: (( merge || 1 ))

  - name: hm9000_z2
    instances: (( merge || 1 ))

  - name: runner_z2
    instances: (( meta.runner_z2_instances || 1 ))